server:
  port: 80
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/taotao
      username: root
      password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true